import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`antialiase`}
      >
        <div className="fixed w-full h-dvh bg-blue-400/5 pointer-events-none z-30"></div>
        {children}
      </body>
    </html>
  );
}
